### ISSUE TITLE
terminusdb.yaml fails to validate due to requestBody in DELETE

### ISSUE THREAD

**Issue by spl** [terminusdb/openapi-specs#3]
The OpenAPI 3.0 specification [disallows `requestBody` in `DELETE`][oas303requestBody]:

> The `requestBody` is only supported in HTTP methods where the HTTP 1.1 specification (RFC 7231) has explicitly defined semantics for request bodies. In other cases where the HTTP spec is vague, `requestBody` SHALL be ignored by consumers.

[oas303requestBody]: https://spec.openapis.org/oas/v3.0.3.html#operationRequestBody

[RFC 7231](https://httpwg.org/specs/rfc7231.html#DELETE):

> A payload within a `DELETE` request message has no defined semantics; sending a payload body on a `DELETE` request might cause some existing implementations to reject the request.

This currently causes `terminusdb.yaml` to fail validation with the Swagger Editor.

Endpoints like `/api/db` and `/api/document` support JSON in the `DELETE` request. I believe the use of the request body is not integral to the semantics of the operation. That is, we could replace the JSON request body with query parameters that serve the same purpose.

The latest release of the OpenAPI specification, v3.1.0, [allows `requestBody` in `DELETE`][oas310requestBody]:

> The `requestBody` is fully supported in HTTP methods where the HTTP 1.1 specification (RFC 7231) has explicitly defined semantics for request bodies. In other cases where the HTTP spec is vague (such as `GET`, `HEAD` and `DELETE`), `requestBody` is permitted but does not have well-defined semantics and SHOULD be avoided if possible.

[oas310requestBody]: https://spec.openapis.org/oas/v3.1.0.html#operationRequestBody

However, the Swagger Editor [does not yet support OpenAPI 3.1][swagger_oas31]. Also, there aren't many [OpenAPI tools][openapi_tools] that support 3.1.

[swagger_oas31]: https://github.com/swagger-api/swagger-parser/issues/1535#issuecomment-936707841
[openapi_tools]: https://openapi.tools/

**Comment by GavinMendelGleason** [comment]
Not allowing `requestBody` in delete was a mistake. We should probably ignore the error if it is possible.

**Comment by spl** [comment]
I like valid things, so I would like to have CI to validate `terminusdb.yaml`; however, it would fail every time. So, would it be better to:

1. add CI validation and look at the always-failing output for other possible failures or
2. not have CI validation?

**Comment by GavinMendelGleason** [comment]
We should ignore the specific error regarding request body in DELETE if it's not too much trouble. Otherwise get rid of CI validation.

**Comment by spl** [comment]
Thanks to <https://github.com/char0n/swagger-editor-validate/pull/126>, we can ignore the error! 🎉
